version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: remake
      POSTGRES_PASSWORD: remake-generator
      POSTGRES_DB: id-generator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
